### ISSUE TITLE
Sometimes corrupt files are left behind when "Save" As fails

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/vimage#12]
This is a follow on to issue #10

Steps to reproduce:

1. Load the image from issue #10
2. "Save As"
3. Set output filter to "All Files"
4. Save file as a name without extension e.g. "phlerb"
5. An error dialog (correctly) appears
5. Notice the output file is created but not usable

Expected behavior:

- No output file is produced, because there was an error

**Comment by ckbruns** [comment]
Reproduced by saving file with .jpg extension - gives error, but also creates as unusable file
Saving with no extension resulted in file saved as .png

**Comment by cmbruns** [comment]
@ckbruns please verify

**Comment by ckbruns** [comment]
Verified
