### ISSUE TITLE
Open image from clipboard

### ISSUE THREAD

**Issue by cmbruns** [cmbruns/vimage#34]

**Comment by ckbruns** [comment]
Want to:
- [x]  copy image on monitor to clipboard using PrtSc key on keyboard
- [x]  paste from clipboard to new file in image
- [x] crop image to desired item
- [x] save image
- [ ] possibly print image?

**Comment by cmbruns** [comment]
Fixed in b76005abd0b236fb0fa541ab8b005c5b964e9dbb
